---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: consul-operator
  name: consul-operator
  namespace: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: consul-operator
  template:
    metadata:
      labels:
        name: consul-operator
    spec:
      serviceAccountName: consuloperator
      restartPolicy: Always
      containers:
      - image: zdq0394/consul-operator:0.1
        name: consul-operator
        command: ["/opt/consul/operator", "consul", "--clusterdomain=cluster.local", "--concurrentworkers=3"]
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
