/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/zdq0394/consul-operator/pkg/apis/consul/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConsuls implements ConsulInterface
type FakeConsuls struct {
	Fake *FakeConsulV1alpha1
	ns   string
}

var consulsResource = schema.GroupVersionResource{Group: "consul.zdq0394.io", Version: "v1alpha1", Resource: "consuls"}

var consulsKind = schema.GroupVersionKind{Group: "consul.zdq0394.io", Version: "v1alpha1", Kind: "Consul"}

// Get takes name of the consul, and returns the corresponding consul object, and an error if there is any.
func (c *FakeConsuls) Get(name string, options v1.GetOptions) (result *v1alpha1.Consul, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(consulsResource, c.ns, name), &v1alpha1.Consul{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Consul), err
}

// List takes label and field selectors, and returns the list of Consuls that match those selectors.
func (c *FakeConsuls) List(opts v1.ListOptions) (result *v1alpha1.ConsulList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(consulsResource, consulsKind, c.ns, opts), &v1alpha1.ConsulList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConsulList{ListMeta: obj.(*v1alpha1.ConsulList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConsulList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested consuls.
func (c *FakeConsuls) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(consulsResource, c.ns, opts))

}

// Create takes the representation of a consul and creates it.  Returns the server's representation of the consul, and an error, if there is any.
func (c *FakeConsuls) Create(consul *v1alpha1.Consul) (result *v1alpha1.Consul, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(consulsResource, c.ns, consul), &v1alpha1.Consul{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Consul), err
}

// Update takes the representation of a consul and updates it. Returns the server's representation of the consul, and an error, if there is any.
func (c *FakeConsuls) Update(consul *v1alpha1.Consul) (result *v1alpha1.Consul, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(consulsResource, c.ns, consul), &v1alpha1.Consul{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Consul), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConsuls) UpdateStatus(consul *v1alpha1.Consul) (*v1alpha1.Consul, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(consulsResource, "status", c.ns, consul), &v1alpha1.Consul{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Consul), err
}

// Delete takes name of the consul and deletes it. Returns an error if one occurs.
func (c *FakeConsuls) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(consulsResource, c.ns, name), &v1alpha1.Consul{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConsuls) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(consulsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConsulList{})
	return err
}

// Patch applies the patch and returns the patched consul.
func (c *FakeConsuls) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Consul, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(consulsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Consul{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Consul), err
}
